"""
EMRY Markdown Generator - Creates pristine, beautifully formatted MD files
"""
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Dict
import re

class MarkdownGenerator:
    def __init__(self, output_dir: str):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_daily_file(self, date: str, messages: List[Dict]) -> str:
        """Generate a pristine markdown file for a specific date"""
        if not messages:
            return None

        # Parse date
        date_obj = datetime.strptime(date, '%Y-%m-%d')
        date_formatted = date_obj.strftime('%B %d, %Y')
        weekday = date_obj.strftime('%A')

        # Group messages by conversation
        conversations = self._group_by_conversation(messages)

        # Build markdown
        lines = []
        lines.append(f"# EMRY - Eternal Memory")
        lines.append(f"## {weekday}, {date_formatted}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Statistics
        total_messages = len(messages)
        platforms = set(m['platform'] for m in messages)
        lines.append(f"**Messages Captured:** {total_messages} | **Platforms:** {', '.join(sorted(platforms))}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Render each conversation
        for i, conv in enumerate(conversations, 1):
            lines.extend(self._render_conversation(conv, i))
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append(f"*Generated by EMRY v2.0 on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

        content = "\n".join(lines)

        # Write to file
        filename = f"{date}.md"
        filepath = self.output_dir / filename
        filepath.write_text(content, encoding='utf-8')

        return str(filepath)

    def _group_by_conversation(self, messages: List[Dict]) -> List[List[Dict]]:
        """Group messages into conversations"""
        conversations = []
        current_conv = []
        last_url = None
        last_time = None

        for msg in messages:
            # New conversation if URL changes or gap > 30 minutes
            if msg['source_url'] != last_url or \
               (last_time and self._time_gap(last_time, msg['captured_at']) > 30):
                if current_conv:
                    conversations.append(current_conv)
                current_conv = []

            current_conv.append(msg)
            last_url = msg['source_url']
            last_time = msg['captured_at']

        if current_conv:
            conversations.append(current_conv)

        return conversations

    def _time_gap(self, time1: str, time2: str) -> int:
        """Calculate time gap in minutes"""
        try:
            t1 = datetime.fromisoformat(time1.replace('Z', '+00:00'))
            t2 = datetime.fromisoformat(time2.replace('Z', '+00:00'))
            return abs((t2 - t1).total_seconds() / 60)
        except:
            return 0

    def _render_conversation(self, messages: List[Dict], conv_number: int) -> List[str]:
        """Render a single conversation"""
        lines = []

        # Conversation header
        first_msg = messages[0]
        platform = first_msg['platform'].title()
        time_start = self._format_time(first_msg['captured_at'])
        title = first_msg.get('title', 'Untitled Conversation')

        lines.append(f"### Conversation {conv_number}: {platform}")
        lines.append(f"**Started:** {time_start}")
        if first_msg['source_url']:
            lines.append(f"**URL:** {first_msg['source_url']}")
        lines.append("")

        # Messages
        for msg in messages:
            role = msg['role'].upper()
            content = self._clean_content(msg['content'])
            timestamp = self._format_time(msg['captured_at'])

            # Role indicator
            role_emoji = "👤" if role == "USER" else "🤖"
            lines.append(f"**{role_emoji} {role}** *({timestamp})*")
            lines.append("")

            # Content (properly indented if code blocks)
            lines.append(content)
            lines.append("")

        lines.append("---")

        return lines

    def _clean_content(self, content: str) -> str:
        """Clean and format content"""
        # Remove excessive whitespace
        content = re.sub(r'\n{3,}', '\n\n', content)

        # Ensure code blocks are properly formatted
        content = content.strip()

        return content

    def _format_time(self, timestamp: str) -> str:
        """Format timestamp nicely"""
        try:
            dt = datetime.fromisoformat(timestamp.replace('Z', '+00:00'))
            return dt.strftime('%I:%M:%S %p')
        except:
            return timestamp

    def generate_index(self, db) -> str:
        """Generate an index file with all dates"""
        start_date, end_date = db.get_date_range()
        if not start_date:
            return None

        lines = []
        lines.append("# EMRY - Master Index")
        lines.append("")
        lines.append("Your eternal memory across all AI conversations.")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Statistics
        stats = db.get_stats()
        lines.append("## Statistics")
        lines.append("")
        lines.append(f"- **Total Messages:** {stats['total_messages']}")
        lines.append(f"- **Total Conversations:** {stats['total_conversations']}")
        lines.append(f"- **Date Range:** {start_date} to {end_date}")
        lines.append("")

        if stats.get('by_platform'):
            lines.append("### Messages by Platform")
            for platform, count in sorted(stats['by_platform'].items()):
                lines.append(f"- **{platform.title()}:** {count} messages")
            lines.append("")

        lines.append("---")
        lines.append("")
        lines.append("## Daily Logs")
        lines.append("")

        # List all daily files
        daily_files = sorted(self.output_dir.glob("????-??-??.md"), reverse=True)
        for filepath in daily_files:
            date = filepath.stem
            date_obj = datetime.strptime(date, '%Y-%m-%d')
            formatted = date_obj.strftime('%B %d, %Y (%A)')
            lines.append(f"- [{formatted}]({filepath.name})")

        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(f"*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*")

        content = "\n".join(lines)

        # Write index
        index_path = self.output_dir / "INDEX.md"
        index_path.write_text(content, encoding='utf-8')

        return str(index_path)

    def regenerate_all(self, db) -> List[str]:
        """Regenerate all markdown files from database"""
        start_date, end_date = db.get_date_range()
        if not start_date or not end_date:
            return []

        generated_files = []

        # Parse dates
        current = datetime.strptime(start_date, '%Y-%m-%d')
        end = datetime.strptime(end_date, '%Y-%m-%d')

        # Generate file for each day
        while current <= end:
            date_str = current.strftime('%Y-%m-%d')
            messages = db.get_messages_by_date(date_str)

            if messages:
                filepath = self.generate_daily_file(date_str, messages)
                if filepath:
                    generated_files.append(filepath)

            current += timedelta(days=1)

        # Generate index
        index_path = self.generate_index(db)
        if index_path:
            generated_files.append(index_path)

        return generated_files
