#Requires -Version 5.1
<#
.SYNOPSIS
    EMRY Auto-Debug - Analyze and prepare error reports for AI

.DESCRIPTION
    Fetches unresolved errors from EMRY, formats them beautifully,
    and prepares them for submission to ChatGPT/Claude/etc.

.EXAMPLE
    .\Auto-Debug.ps1
    .\Auto-Debug.ps1 -CopyToClipboard
    .\Auto-Debug.ps1 -OpenInBrowser
#>

param(
    [int]$Port = 8766,
    [switch]$CopyToClipboard,
    [switch]$OpenInBrowser
)

$ErrorActionPreference = 'Stop'

# ============================================================================
# Functions
# ============================================================================

function Get-UnresolvedErrors {
    try {
        $serverUrl = "http://127.0.0.1:$Port"
        $response = Invoke-RestMethod -Uri "$serverUrl/errors/unresolved" -Method GET -TimeoutSec 5

        if ($response.ok) {
            return $response.errors
        }
    } catch {
        Write-Warning "Could not fetch errors from EMRY: $_"
        Write-Host "Make sure EMRY server is running on port $Port" -ForegroundColor Yellow
        exit 1
    }
    return @()
}

function Format-ErrorForAI {
    param($Errors)

    if ($Errors.Count -eq 0) {
        return $null
    }

    $report = @"
# PowerShell Error Report - Auto-Generated by EMRY

I encountered the following PowerShell errors. Can you help me understand and fix them?

## Summary
- **Total Errors:** $($Errors.Count)
- **Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

---

"@

    foreach ($error in $Errors) {
        $timestamp = if ($error.detected_at) {
            (Get-Date $error.detected_at -Format 'yyyy-MM-dd HH:mm:ss')
        } else {
            'Unknown'
        }

        $report += @"

## Error #$($error.id)

**Time:** $timestamp
**Session:** $($error.session_id)
**Transcript:** ``$($error.transcript_path)``

### Error Message
``````
$($error.error_text)
``````

### Context
``````
$($error.context)
``````

---

"@
    }

    $report += @"

## Questions
1. What caused these errors?
2. How can I fix them?
3. Are there any best practices I should follow to avoid this in the future?

---
*Generated by EMRY v2.0 - Eternal Memory System*
"@

    return $report
}

# ============================================================================
# Main
# ============================================================================

Write-Host ""
Write-Host "╔════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║          EMRY Auto-Debug System                ║" -ForegroundColor Cyan
Write-Host "╚════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

Write-Host "🔍 Fetching unresolved errors..." -ForegroundColor Yellow

$errors = Get-UnresolvedErrors

if ($errors.Count -eq 0) {
    Write-Host "✅ No unresolved errors found! Your system is clean." -ForegroundColor Green
    Write-Host ""
    exit 0
}

Write-Host "⚠️  Found $($errors.Count) unresolved error(s)" -ForegroundColor Yellow
Write-Host ""

# Format errors for AI
$report = Format-ErrorForAI -Errors $errors

# Display report
Write-Host "══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  Generated Error Report" -ForegroundColor Cyan
Write-Host "══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host $report -ForegroundColor White
Write-Host ""

# Copy to clipboard
if ($CopyToClipboard -or $OpenInBrowser) {
    try {
        $report | Set-Clipboard
        Write-Host "✅ Report copied to clipboard!" -ForegroundColor Green
        Write-Host ""
    } catch {
        Write-Warning "Could not copy to clipboard: $_"

        # Save to file instead
        $tempFile = Join-Path $env:TEMP "emry_error_report_$(Get-Date -Format 'yyyyMMdd_HHmmss').md"
        $report | Set-Content $tempFile -Encoding UTF8
        Write-Host "📄 Report saved to: $tempFile" -ForegroundColor Cyan
        Write-Host ""
    }
}

# Open in browser
if ($OpenInBrowser) {
    Write-Host "🌐 Opening ChatGPT in browser..." -ForegroundColor Cyan

    $chatGptUrl = "https://chat.openai.com/"

    try {
        Start-Process $chatGptUrl
        Write-Host "✅ Browser opened! Paste the report from your clipboard." -ForegroundColor Green
    } catch {
        Write-Warning "Could not open browser: $_"
        Write-Host "Please visit: $chatGptUrl" -ForegroundColor Yellow
        Write-Host "Then paste the report from your clipboard" -ForegroundColor Yellow
    }

    Write-Host ""
}

Write-Host "══════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  Next Steps:" -ForegroundColor Green
Write-Host "══════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
Write-Host "  1. Copy the report above (or use -CopyToClipboard)" -ForegroundColor Yellow
Write-Host "  2. Paste it into ChatGPT, Claude, or your preferred AI" -ForegroundColor Yellow
Write-Host "  3. Get solutions and fix the errors!" -ForegroundColor Yellow
Write-Host "  4. Mark errors as resolved in EMRY" -ForegroundColor Yellow
Write-Host ""
Write-Host "Tip: Use -OpenInBrowser to automatically open ChatGPT" -ForegroundColor Gray
Write-Host ""
